services:
  # PostgreSQL database
  db:
    # Uses postgres:15 as our base image
    image: postgres:15
    # Sets enviornment variables for PostgreSQL container
    environment:
      # database name
      POSTGRES_DB: bobyard_db
      # superuser
      POSTGRES_USER: postgres
      # superuser password
      POSTGRES_PASSWORD: password
      # default user
      PGUSER: postgres
    # Maps postgres_data volume to containers data directory
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Maps port 5432 on the host to container
    ports:
      - "5432:5432"
    # Defines the health check for the db service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5

  # Django backend
  backend:
    # built from backed/Dockerfile
    build: ./backend
    # Maps port 8000 on the host to container
    ports:
      - "8000:8000"
    # Ensures db service starts before this (does not guarentee the db is fully initialized)
    # Guarentees the db is fully intialized
    depends_on:
      db:
        condition: service_healthy
    # Sets enviornment variables for Django app
    environment:
      - DB_NAME=bobyard_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SECRET_KEY=your-secure-random-key
    volumes:
      # Mounts ./backend directory to /app in the container
      # Syncs local code with container (enables live code reloading during development)
      - ./backend:/app
      # Mounts comments.json from local directory to /app/comments.json in the container
      # Used to seed data
      - ./comments.json:/app/comments.json
    # Overrides Dockerfile CMD
    # Runs shell command to:
    # Generate Django migration files based on model changes
    # Applies db migrations
    # Starts Django development server on port 8000
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    # defines the health check for the backend service
    healthcheck:
      test:
        ["CMD-SHELL", "curl -fs http://localhost:8000/api/comments/ || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  # React frontend
  frontend:
    # built from frontend/Dockerfile
    build: ./frontend
    # Maps port 3000 on the host to container
    ports:
      - "3000:3000"
    # Ensures backend service starts before this
    # Guarentees the bacvkend is fully intialized
    depends_on:
      backend:
        condition: service_healthy
    # Sets environment variables for React app
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    volumes:
      # Mounts ./frontend directory to /app in the container
      - ./frontend:/app
      # Creates an anonymous volume in the container to preserve node modules
      - /app/node_modules

# Volumes for persistent data storage across container restarts
volumes:
  postgres_data:
